### ISSUE TITLE
new project is created in current working directory instead of new folder

### ISSUE THREAD

**Issue by wes566** [muenzpraeger/lwc-create-app#3]
### Summary

Maybe this is by design but just in case it's not...

When I create a new app I would expect a new folder to get created for that app, but the app is created in cwd.

### Steps To Reproduce:

```sh
cd ~
npx lwc-create-app my-app
```

### Expected result

New project is created at `~/my-app`

### Actual result

New project is created at `~`

**Comment by muenzpraeger** [comment]
Does that happen to you outside of the home folder?

**Comment by muenzpraeger** [comment]
The error message in #2 is related to that.

**Comment by wes566** [comment]
@muenzpraeger Yes, I just used `~` as an example, I actually used `/Users/wes/source/repos` and still hit this issue

**Comment by muenzpraeger** [comment]
I just ran the command and can't reproduce it. Is that on Linux or Mac?

![Screenrecording](https://muenzpraeger.s3-eu-west-1.amazonaws.com/screenrecording-lwc-create-app-dirs-github.gif)

**Comment by wes566** [comment]
This is on macOS.  Figured out the problem, I was using node v8.11.3

After updating to node v10.15.3 this issue and #4 were fixed.

Maybe the tool should hard block if the node version is below 10?

**Comment by wes566** [comment]
BTW, I selected "node" instead of "yarn" originally... I just tried again on node v8.x and selected yarn and now I see there are many errors shown that make it apparent this version of node won't work, but if you select NPM there is 1 small error shown that gets scrolled off the screen, so that's why I missed it.

When selecting yarn:
![image](https://user-images.githubusercontent.com/3293318/58595240-de359d80-8224-11e9-8b5f-91c5a4920d48.png)

When selecting node (this gets scrolled off the screen immediately):
![image](https://user-images.githubusercontent.com/3293318/58595258-ee4d7d00-8224-11e9-8096-c2f0fa49aa27.png)

In both cases the tool continues, I'm thinking maybe just have the tool do a node version check right up front and exit if not 10+... @muenzpraeger would you like me to open an issue for that feature request?

**Comment by muenzpraeger** [comment]
Thanks for digging that, @wes566! I'm working already on a PR with another change, so I'll add that check.
