### ISSUE TITLE
App name is "undefined" in final tool output

### ISSUE THREAD

**Issue by wes566** [muenzpraeger/lwc-create-app#4]
### Summary

After creating a new app the final message says "Created undefined" instead of the app's name.

![image](https://user-images.githubusercontent.com/3293318/58578612-0eb61100-81fe-11e9-9e09-6b5e4a09b00a.png)

### Steps To Reproduce:

1. `npx lwc-create-app my-app`

### Expected result

Tool output says something like "Created my-app in /foo/dir"

### Actual result

Tool output says "Created undefined in /foo/dir"

**Comment by wes566** [comment]
This only happens when using a version of node less than v10 and when you choose "npm" instead of "yarn"

**Comment by muenzpraeger** [comment]
New version published
