### ISSUE TITLE
example for resources in config file

### ISSUE THREAD

**Issue by mshanemc** [muenzpraeger/lwc-create-app#41]
**What is missing from the application? Please describe.**
The example config file has an empty `"resources": []`.  It's not obvious what to do with that...list out the folders I want to copy?

**Describe the solution you'd like**
It turns out that the elements in that array are supposed to be formatted { "from": "x", "to": "y"}

**Describe alternatives you've considered**
I had to dig into the code in the your webpack config generation to figure out the from/to thing.  Also considered learning webpack but am avoiding that.

**Comment by muenzpraeger** [comment]
Good find. Will update the example.

In the sample app that you create via `lwc-create-app` is also an `lwc-services.config.js` file with a value for that populated.

**Comment by mshanemc** [comment]
ahh...was working on migrating an existing project and didn't have the luxury of starting from a new project.  That's a whole valid path

**Comment by muenzpraeger** [comment]
Fixed via #46
