### ISSUE TITLE
error if ~/.gitconfig doesn't exist

### ISSUE THREAD

**Issue by kevinv11n** [muenzpraeger/lwc-create-app#5]
### Summary

If `~/.gitconfig` doesn't exist then the tool errors out with a confusing message: `Email required`

### Steps To Reproduce:

1. Remove `~/.gitconfig` if it doesn't exist
1. Run `npx lwc-create-app your-app-name`

### Expected result

Tool should run and prompt for the email.

### Actual result

Tool exits with confusing error message: `Email required`

**Comment by muenzpraeger** [comment]
I couldn't re-create that. Did you run that with the previous internal version, or did that happen with the public version?

**Comment by Stefanvdk** [comment]
I had the `Email required` error message as reported above. Adding a user.email to the gitconfig file fixed it for me:
`git config --global user.email johndoe@example.com`

**Comment by Jeff17Robbins** [comment]
I had the same problem on Windows 10.  Adding `user.email` fixed it.  Removing `user.email` reproduced the problem.

**Comment by muenzpraeger** [comment]
Thanks @Jeff17Robbins - that detailed stacktrace helped to nail the issue as I couldn't repro on my machine.
