### ISSUE TITLE
Custom server/index.js doesnt work in run watch

### ISSUE THREAD

**Issue by neidenmark** [muenzpraeger/lwc-create-app#56]
### Summary

Custom server/index.js doesnt work in run watch

### Steps To Reproduce:

Add a app.get("/test", (req,res) => { res.send("hello"); }); to src/server/index.js

### Expected result

surfing to localhost:3001/test should yield "hello"

### Actual result

This works once I pushed to prod (in my case heroku) but it doesnt work in local context using npm run watch

**Comment by muenzpraeger** [comment]
`watch` mode runs only `webpack-dev-server` for LWC development. If you want to spawn up Express besides it during development you’ve to start it separately, based on your needs, with a script.

**Comment by muenzpraeger** [comment]
Just for reference for those you read this issue later, this is a simple example `express-dev.js` file that I use in these kind of projects:

```
const path = require('path');
const express = require('express');

const customServer = require(path.resolve('./lib/server/')).default;

const app = express();

customServer(app);

app.listen(3002, () => {
    // eslint-disable-next-line no-console
    console.log('Yay, local server started');
});
```

And starting (with a TypeScript based Express project) like this:

```
"watch": "lwc-services watch & yarn watch:server",
"watch:server": "tsc -b ./src/server && node scripts/express-dev.js"
```

**Comment by jordanbaucke** [comment]
@muenzpraeger 

What is the purpose of `src/server/index.js` in this scenario then? 

Thanks,

Jordan

**Comment by muenzpraeger** [comment]
That's the entrypoint file for your custom Express (backend) logic. I'll add an example to the scaffolding project, good call!

```
export default function(app) {
    // Custom route
    app.get('/api/1/something', (req, res) => {
        // do stuff
    });

}
```
