### ISSUE TITLE
npm run watch error on fresh install

### ISSUE THREAD

**Issue by andrew6767** [muenzpraeger/lwc-create-app#57]
### Summary

On a fresh install of lwc-create-app running the npm run watch command fails with error below

### Steps To Reproduce:

1.  npx lwc-create-app hello-world
1.  npm run watch

### Actual result

`npm ERR! missing script: watch`

### Additional information

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'watch' ]
2 info using npm@5.6.0
3 info using node@v9.7.1
4 verbose stack Error: missing script: watch
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:115:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:402:5
4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:357:45)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:400:3)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:160:5)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:280:12
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:532:3)
5 verbose cwd /Users/johnsmith/Documents/playground/lwc
6 verbose Darwin 18.0.0
7 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "watch"
8 verbose node v9.7.1
9 verbose npm  v5.6.0
10 error missing script: watch
11 verbose exit [ 1, true ]`

**Comment by muenzpraeger** [comment]
Can you please upgrade to the current LTS version on node (10.x), which is set as the minimum required version in the `package.json` file.

**Comment by andrew6767** [comment]
thank you! that's fixed my issue. Apologies for not spotting this.
