### ISSUE TITLE
npm link module during development

### ISSUE THREAD

**Issue by Templarian** [muenzpraeger/lwc-create-app#58]
### Summary

Understanding NPM modules are a WIP, but trying to play with idea and noticing a small dev workflow issue. When using `npm link` the loaders do not seem to want to process `.html` template files.

### Steps To Reproduce:

1. Create an app with `lwc-create-app`
    - update the `package.json` name to `foo-bar`.
    - Add a simple `src/modules/hello/world.js`  / `world.html`
    - run `npm link` 
1. In another `lwc-create-app`
    - run `npm link foo-bar` (may need to relink after any `npm install`'s)

### Expected result

Component renders. This works as expected from NPM.

### Actual result

```text
ERROR in </filename.html> 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <template>
```

### Additional information

https://github.com/babel/babel-loader/issues/149 Might be related to this?

I tried to look through the code to pinpoint where it might be failing for symlinks. Same issue with `@scoped/packages` and non scoped names.

**Comment by muenzpraeger** [comment]
Good find!! I was playing with the same idea on Friday, with exactly the same issue. ;-)

**Comment by muenzpraeger** [comment]
You've got to use a custom `webpack.config.js` if you want to link locally.

```
module.exports = {
    resolve: {
        symlinks: false
    }
};
```

**Comment by Templarian** [comment]
Awesome! Works perfectly just tried it out.

Thanks!
