### ISSUE TITLE
jest tests don't resolve modules in non-standard directory

### ISSUE THREAD

**Issue by mshanemc** [muenzpraeger/lwc-create-app#61]
### Summary

I'm using a folder structure that isn't src/modules/namespace/module (my top-level is called `client-src` instead of `src`)

Everything but the jest-preset stuff seems to be correctly picking up my lwc.config file's `moduleDir`

### Steps To Reproduce:

repro repo here: https://github.com/mshanemc/deploy-to-sfdx

Create a test in any LWC
try running the test

### Expected result

tests run

### Actual result

 FAIL  client-src/modules/route/deployMessages/__tests__/deployMessages.test.js
  ● Test suite failed to run

    Cannot find module 'route/deployMessages' from 'deployMessages.test.js'

### Additional information
I can get the test to run by importing the component with a relative path  ../deployMessages.  But then it fails to find any components that the outer level component contains because of the same resolver issue.

**Comment by muenzpraeger** [comment]
Can you please install version `1.2.3-beta.0` of `lwc-services` and see if that fixes your issue? TY!

**Comment by mshanemc** [comment]
@muenzpraeger yep, that fixes it nicely.  Thanks!
