### ISSUE TITLE
Code is referenced via absolute paths

### ISSUE THREAD

**Issue by eltoroit** [muenzpraeger/lwc-create-app#71]
### Summary

I tried using this code to build an app for Electron, but I discovered the code generated uses full paths rather than relative ones.

### Steps To Reproduce:

1.  Build the code (`npm run build`)
1. Notice the paths generated in the `/my-app/dist/index.html` file are absolute

### Expected result

The paths should be relative, I guess if you are building a server does not really matter but for Electron it's critical and possibly other platforms may be affected as well.

### Actual result

Generated absolute paths

### Additional information

This code needs to be updated

node_modules/lwc-services/lib/utils/webpack/webpack-builder.js:84
FROM:	`publicPath: '/'`
TO:		`publicPath: './'`

node_modules/lwc-services/lib/utils/webpack/webpack-builder.js:114
FROM:	`publicPath: '/'`
TO:		`publicPath: './'`

**Comment by muenzpraeger** [comment]
This is WAD. For your use case you can use a custom webpack config with the `-w` flag of `lwc-services` to override the built-in behavior.

**Comment by eltoroit** [comment]
Sorry, but I do not quite understand your solution. What should the value for the `-w` flag be? and how do I get a custom webpack? Which files do I need to copy/edit?

**Comment by muenzpraeger** [comment]
All commands have a `-w` flag, like [here](https://github.com/muenzpraeger/lwc-create-app/blob/master/README.md#lwc-services-build), where you can pass the path to a `webpack.config.js`. That way you can add/override the built-in config.

More info on that can be read in the [webpack documentation](https://webpack.js.org/configuration/).
