### ISSUE TITLE
buildDir does not copy resources to the desired output folder.

### ISSUE THREAD

**Issue by eltoroit** [muenzpraeger/lwc-create-app#73]
### Summary

The file `lwc-services.config.js` allows you to specify an output directory using the `buildDir`. Although the code gets placed in that folder the resources folder get copied somewhere else.

### Steps To Reproduce:

1.  Build the project (`npm run build`)
1. Noticed the resource folder is not in the correct path.

### Expected result

Static resources should be copied as a subfolder of the built path (`buildDir`).

### Actual result

Resource folder and files get copied to the wrong destination.

### Additional information

This can be fixed by updating this file

node_modules/lwc-services/lib/config/webpack.config.js:32
FROM:	`to: path.join(process.cwd(), resource.to)`
TO:		`to: path.join(OUTPUT_DIR, resource.to)`

**Comment by muenzpraeger** [comment]
That’s WAD. You’ve to specify the desired directory in the `to` parameter.

https://github.com/muenzpraeger/lwc-create-app/blob/master/packages/lwc-services/example/lwc-services.config.js#L20

**Comment by eltoroit** [comment]
I set the entry to 

```
resources: [
    { from: 'src/resources', to: '../ELTOROIT/src/LWC4ELECTRON/resources' }
]
```

and it worked.

Thanks.
