### ISSUE TITLE
Watch command ignores mode Parameter

### ISSUE THREAD

**Issue by Renji-XD** [muenzpraeger/lwc-create-app#8]
### Summary

lwc-services watch does not apply the mode parameters

### Expected result

lwc-services watch -m production generates the production bundle of the app

### Actual result

lwc-services watch -m production generates the development bundle of the app

### Additional information

While the build command updates the mode [here](https://github.com/muenzpraeger/lwc-create-app/blob/master/packages/lwc-services/src/commands/build.ts#L95), the watch command does not do it.

**Comment by muenzpraeger** [comment]
Fixed and new version published. Thanks for opening the issue!
